config/routes.rb
Rails.application.routes.draw do
    root "sessions#new"
    get '/:locale'   => 'sessions#new',as:"locale" 
    get '/' => redirect("/ja")
    post '/',        to: 'sessions#create'
    get 'password_resets/new'
    get 'password_resets/edit'
  scope ":/locale", locale:/en|ja/ do
  # scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    get  '/',        to: 'sessions#new'
    post '/',        to: 'sessions#create'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/privacy', to: 'static_pages#privacy'
    get  '/term',    to: 'static_pages#term'
    get  '/language',to: 'static_pages#language'
    get  '/search',  to: 'static_pages#search'
    get  '/searchresult', to: 'static_pages#searchresult'
    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'
    delete '/logout',    to: 'sessions#destroy'
    get  '/tester',      to: 'tests#new'
    post '/tester',      to: 'tests#create'
    get  '/mytests',     to: 'tests#my_index'
    get  '/mytests/:id', to: 'tests#my_show'
    resources :users
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :tests do
      resources :questions do
        member do
          get :answerring
          post :post_answerring
        end
        resources :selects, :answers, only: [:new, :create, :edit, :destroy]
      end
    end
    resources :testeds do
      resources :tests do
        resources :answers, only: [:index, :show, :destroy]
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to t(:"Top"),    root_path %></li>
      <li><%= link_to t(:"Help"),    help_path %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= t(:"Language") %><b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "English", locale_path(locale:"en") %></li>
          <li><%= link_to "日本語", locale_path(locale:"ja") %></li>
        </ul>
      </li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-md navbar-light sticky-top"
  style="background-color:#fff; box-shadow:0 2px rgba(0,0,0,0.4);">
  <button id='scroll_top' class="btn_fix_top btn-lg btn-primary">▲</button>
  <button id='scroll_bottom' class="btn_fix_bottom btn-lg btn-primary">▼</button>
  <div class="container">
    <%= link_to "", root_path, id: "logo" %>
    <a class="navbar-brand" href="/">
      <%= image_tag 'mytest.png', size: '120x48'%>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarResponsive">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto navbar-right">
        <li class="nav-item center"><%= link_to t(:"Top"),  root_path %></li>
        <li class="nav-item center"><%= link_to t(:"Help"), help_path %></li>
        <% if logged_in? %>
          <li class="dropdown nav-item center"><%= link_to t(:"Users"), users_path %></li>
          <li class="dropdown nav-item center">
            <a href="#" class="dropdown-toggle nav-item center" data-toggle="dropdown">
              <%= t(:"Account") %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li class="nav-item center"><%= link_to t(:"Profile"), current_user %></li>
              <li class="nav-item center"><%= link_to t(:"Settings"), edit_user_path(current_user) %></li>
              <li class="divider nav-item center"></li>
              <li class="nav-item center">
                <%= link_to t(:"Log out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="dropdown nav-item center">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t(:"Log in") %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li class="nav-item center"><%= link_to t(:"Log in"), root_path %></li>
              <li class="nav-item center"><%= link_to t(:"Sign up"), new_user_path %></li>
            </ul>
          </li>
        <% end %>
        <li class="dropdown nav-item center">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t(:"Language") %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li class="nav-item center"><%= link_to "English", locale_path(locale:"en") %></li>
            <li class="nav-item center"><%= link_to "日本語", locale_path(locale:"ja") %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_header_menu.html.erb
<li><%= link_to t(:"Top"),  root_path %></li>
<li><%= link_to t(:"Help"), help_path %></li>
<% if logged_in? %>
  <li><%= link_to t(:"Users"), users_path %></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= t(:"Account") %> <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to t(:"Profile"), current_user %></li>
      <li><%= link_to t(:"Settings"), edit_user_path(current_user) %></li>
      <li class="divider"></li>
      <li>
        <%= link_to t(:"Log out"), logout_path, method: :delete %>
      </li>
    </ul>
  </li>
<% else %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= t(:"Log in") %><b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to t(:"Log in"), root_path %></li>
      <li><%= link_to t(:"Sign up"), new_user_path %></li>
    </ul>
  </li>
<% end %>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= t(:"Language") %><b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li><%= link_to "English", locale_path(locale:"en") %></li>
    <li><%= link_to "日本語", locale_path(locale:"ja") %></li>
  </ul>
</li>

app/views/layouts/_header_menu_sp.html.erb
<li><%= link_to t(:"Top"),  root_path %></li>
<li><%= link_to t(:"Help"), help_path %></li>
<% if logged_in? %>
  <li><%= link_to t(:"Users"), users_path %></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= t(:"Account") %> <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to t(:"Profile"), current_user %></li>
      <li><%= link_to t(:"Settings"), edit_user_path(current_user) %></li>
      <li class="divider"></li>
      <li>
        <%= link_to t(:"Log out"), logout_path, method: :delete %>
      </li>
    </ul>
  </li>
<% else %>
  <li class="dropdown">
    <li><%= link_to t(:"Log in"), root_path %></li>
    <li><%= link_to t(:"Sign up"), new_user_path %></li>
    <li><%= link_to "English", locale_path(locale:"en") %></li>
    <li><%= link_to "日本語", locale_path(locale:"ja") %></li>
    <li class="close">閉じる</li>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://m.w3newbie.com/you-tube.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></%#> %>
  </head>
  <body>
    <div id="top_page"></div> <!-- 画面トップへのスクロール用 -->
    <%= render 'layouts/header' %>
    <div class = "container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <div id="bottom_page"></div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </body>
  <script>
    document.getElementById('scroll_top').addEventListener('click',function(){
      $("html,body").animate({scrollTop:$('#top_page').offset().top});
    });
    document.getElementById('scroll_bottom').addEventListener('click',function(){
      $("html,body").animate({scrollTop:$('#bottom_page').offset().top});
    });
  </script>
</html>